
package com.openclassrooms.biblioback.ws.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestPort", targetNamespace = "http://test.ws.biblioback.openclassrooms.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestPort {


    /**
     * 
     * @param borrowingAddRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BorrowingAddResponse
     */
    @WebMethod
    @WebResult(name = "borrowingAddResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingAddResponse")
    public BorrowingAddResponse borrowingAdd(
        @WebParam(name = "borrowingAddRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingAddRequest")
        BorrowingAddRequest borrowingAddRequest);

    /**
     * 
     * @param bookAddRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BookAddResponse
     */
    @WebMethod
    @WebResult(name = "bookAddResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "bookAddResponse")
    public BookAddResponse bookAdd(
        @WebParam(name = "bookAddRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "bookAddRequest")
        BookAddRequest bookAddRequest);

    /**
     * 
     * @param borrowingReturnRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BorrowingReturnResponse
     */
    @WebMethod
    @WebResult(name = "borrowingReturnResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingReturnResponse")
    public BorrowingReturnResponse borrowingReturn(
        @WebParam(name = "borrowingReturnRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingReturnRequest")
        BorrowingReturnRequest borrowingReturnRequest);

    /**
     * 
     * @param borrowingGetExpiredRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BorrowingGetExpiredResponse
     */
    @WebMethod
    @WebResult(name = "borrowingGetExpiredResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingGetExpiredResponse")
    public BorrowingGetExpiredResponse borrowingGetExpired(
        @WebParam(name = "borrowingGetExpiredRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingGetExpiredRequest")
        BorrowingGetExpiredRequest borrowingGetExpiredRequest);

    /**
     * 
     * @param appUserAddRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.AppUserAddResponse
     */
    @WebMethod
    @WebResult(name = "appUserAddResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "appUserAddResponse")
    public AppUserAddResponse appUserAdd(
        @WebParam(name = "appUserAddRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "appUserAddRequest")
        AppUserAddRequest appUserAddRequest);

    /**
     * 
     * @param borrowingExtendRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BorrowingExtendResponse
     */
    @WebMethod
    @WebResult(name = "borrowingExtendResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingExtendResponse")
    public BorrowingExtendResponse borrowingExtend(
        @WebParam(name = "borrowingExtendRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingExtendRequest")
        BorrowingExtendRequest borrowingExtendRequest);

    /**
     * 
     * @param borrowingGetAllRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BorrowingGetAllResponse
     */
    @WebMethod
    @WebResult(name = "borrowingGetAllResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingGetAllResponse")
    public BorrowingGetAllResponse borrowingGetAll(
        @WebParam(name = "borrowingGetAllRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingGetAllRequest")
        BorrowingGetAllRequest borrowingGetAllRequest);

    /**
     * 
     * @param appUserValidityCheckRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.AppUserValidityCheckResponse
     */
    @WebMethod
    @WebResult(name = "appUserValidityCheckResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "appUserValidityCheckResponse")
    public AppUserValidityCheckResponse appUserValidityCheck(
        @WebParam(name = "appUserValidityCheckRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "appUserValidityCheckRequest")
        AppUserValidityCheckRequest appUserValidityCheckRequest);

    /**
     * 
     * @param borrowingGetRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BorrowingGetResponse
     */
    @WebMethod
    @WebResult(name = "borrowingGetResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingGetResponse")
    public BorrowingGetResponse borrowingGet(
        @WebParam(name = "borrowingGetRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingGetRequest")
        BorrowingGetRequest borrowingGetRequest);

    /**
     * 
     * @param bookGetAllRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BookGetAllResponse
     */
    @WebMethod
    @WebResult(name = "bookGetAllResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "bookGetAllResponse")
    public BookGetAllResponse bookGetAll(
        @WebParam(name = "bookGetAllRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "bookGetAllRequest")
        BookGetAllRequest bookGetAllRequest);

    /**
     * 
     * @param borrowingGetCurrentRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BorrowingGetCurrentResponse
     */
    @WebMethod
    @WebResult(name = "borrowingGetCurrentResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingGetCurrentResponse")
    public BorrowingGetCurrentResponse borrowingGetCurrent(
        @WebParam(name = "borrowingGetCurrentRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "borrowingGetCurrentRequest")
        BorrowingGetCurrentRequest borrowingGetCurrentRequest);

    /**
     * 
     * @param appUserGetAllRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.AppUserGetAllResponse
     */
    @WebMethod
    @WebResult(name = "appUserGetAllResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "appUserGetAllResponse")
    public AppUserGetAllResponse appUserGetAll(
        @WebParam(name = "appUserGetAllRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "appUserGetAllRequest")
        AppUserGetAllRequest appUserGetAllRequest);

    /**
     * 
     * @param appUserGetByIdRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.AppUserGetByIdResponse
     */
    @WebMethod
    @WebResult(name = "appUserGetByIdResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "appUserGetByIdResponse")
    public AppUserGetByIdResponse appUserGetById(
        @WebParam(name = "appUserGetByIdRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "appUserGetByIdRequest")
        AppUserGetByIdRequest appUserGetByIdRequest);

    /**
     * 
     * @param bookGetRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BookGetResponse
     */
    @WebMethod
    @WebResult(name = "bookGetResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "bookGetResponse")
    public BookGetResponse bookGet(
        @WebParam(name = "bookGetRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "bookGetRequest")
        BookGetRequest bookGetRequest);

    /**
     * 
     * @param bookGetByIdRequest
     * @return
     *     returns com.openclassrooms.biblioback.ws.test.BookGetByIdResponse
     */
    @WebMethod
    @WebResult(name = "bookGetByIdResponse", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "bookGetByIdResponse")
    public BookGetByIdResponse bookGetById(
        @WebParam(name = "bookGetByIdRequest", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", partName = "bookGetByIdRequest")
        BookGetByIdRequest bookGetByIdRequest);

}
