
package com.openclassrooms.biblioback.ws.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestPortService", targetNamespace = "http://test.ws.biblioback.openclassrooms.com", wsdlLocation = "http://localhost:8080/ws/test.wsdl")
public class TestPortService
    extends Service
{

    private final static URL TESTPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTPORTSERVICE_EXCEPTION;
    private final static QName TESTPORTSERVICE_QNAME = new QName("http://test.ws.biblioback.openclassrooms.com", "TestPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/test.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTPORTSERVICE_WSDL_LOCATION = url;
        TESTPORTSERVICE_EXCEPTION = e;
    }

    public TestPortService() {
        super(__getWsdlLocation(), TESTPORTSERVICE_QNAME);
    }

    public TestPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTPORTSERVICE_QNAME, features);
    }

    public TestPortService(URL wsdlLocation) {
        super(wsdlLocation, TESTPORTSERVICE_QNAME);
    }

    public TestPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTPORTSERVICE_QNAME, features);
    }

    public TestPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestPort
     */
    @WebEndpoint(name = "TestPortSoap11")
    public TestPort getTestPortSoap11() {
        return super.getPort(new QName("http://test.ws.biblioback.openclassrooms.com", "TestPortSoap11"), TestPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestPort
     */
    @WebEndpoint(name = "TestPortSoap11")
    public TestPort getTestPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://test.ws.biblioback.openclassrooms.com", "TestPortSoap11"), TestPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTPORTSERVICE_EXCEPTION!= null) {
            throw TESTPORTSERVICE_EXCEPTION;
        }
        return TESTPORTSERVICE_WSDL_LOCATION;
    }

}
